import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const schema=await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8');
const ids={a:'00000000-0000-0000-0000-000000000001',b:'00000000-0000-0000-0000-000000000002',admin:'00000000-0000-0000-0000-000000000003'};
let checks=0;
const eq=(a,b)=>{assert.deepEqual(a,b);checks++;};
for(const partial of [false,true]){
 const db=new PGlite();
 try{
  await db.exec(`create role anon;create role authenticated;create schema auth;
   create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
   create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
   grant usage on schema auth to anon,authenticated;
   insert into auth.users(id) values('${ids.a}'),('${ids.b}'),('${ids.admin}');`);
  if(partial)await db.exec("create type user_role as enum('user','admin');");
  await db.exec(schema);
  await db.exec(`update profiles set role='admin' where id='${ids.admin}';`);
  const login=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec(id?'set role authenticated':'set role anon');};
  const call=async(name,args)=> (await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as value`,args)).rows[0].value;
  const fail=async(fn)=>{await assert.rejects(fn);checks++;};
  eq((await db.query('select * from documents')).rows.length,0);
  eq((await db.query('select * from profiles')).rows.length,3);
  const payload={title:'테스트',content:'# 본문',summary:'소개',document_type:'other',tags:['학교','테스트'],related_ids:[]};
  await login(ids.a);
  const doc=await call('save_document',[payload,null,null]);
  eq((await db.query('select * from document_revisions')).rows.length,1);
  await fail(()=>db.query("update profiles set role='admin' where id=$1",[ids.a]));
  await fail(()=>db.query("update profiles set is_suspended=false where id=$1",[ids.a]));
  await fail(()=>db.query("update documents set is_featured=true where id=$1",[doc]));
  await fail(()=>call('admin_action',['document',doc,{is_locked:true}]));
  await login(ids.b);
  await call('save_document',[{...payload,title:'변경',content:'수정 본문',edit_summary:'공동 편집'},doc,1]);
  eq((await db.query('select author_id from documents where id=$1',[doc])).rows[0].author_id,ids.a);
  await fail(()=>call('save_document',[{...payload,edit_summary:'충돌'},doc,1]));
  const rev=(await db.query('select id from document_revisions where revision_number=1')).rows[0].id;
  await call('restore_revision',[rev,2]);
  eq((await db.query('select title,revision from documents where id=$1',[doc])).rows[0],{title:'테스트',revision:3});
  const before=(await db.query('select updated_at from documents where id=$1',[doc])).rows[0].updated_at;
  await call('increment_document_view',[doc]);
  eq((await db.query('select updated_at from documents where id=$1',[doc])).rows[0].updated_at,before);
  const comment=await call('write_comment',[doc,'댓글',null,null]);
  const reply=await call('write_comment',[doc,'답글',comment,null]);
  await fail(()=>call('write_comment',[doc,'중첩 답글',reply,null]));
  await fail(()=>call('write_comment',[doc,'x'.repeat(501),null,null]));
  const other=await call('save_document',[{...payload,title:'다른 문서'},null,null]);
  await fail(()=>call('write_comment',[other,'다른 문서 답글',comment,null]));
  await call('toggle_like',[comment]);
  eq((await db.query('select * from comment_likes')).rows.length,1);
  await call('toggle_like',[comment]);
  eq((await db.query('select * from comment_likes')).rows.length,0);
  await login(ids.a);
  await fail(()=>call('write_comment',[doc,'타인 댓글 수정',null,comment]));
  await fail(()=>call('delete_comment',[comment]));
  const person=await call('save_document',[{...payload,title:'인물',document_type:'student',subject_consent:true},null,null]);
  await login(null);
  eq((await db.query('select * from documents where id=$1',[person])).rows.length,0);
  eq((await db.query('select * from document_revisions where document_id=$1',[person])).rows.length,0);
  await login(ids.admin);
  await call('admin_action',['verify_subject',person,{subject_id:ids.b}]);
  await login(ids.a);
  await fail(()=>call('set_person_consent',[person,true]));
  await fail(()=>call('save_document',[{...payload,document_type:'other',edit_summary:'우회'},person,1]));
  await login(ids.b);
  await call('set_person_consent',[person,true]);
  const pc=await call('write_comment',[person,'인물 댓글',null,null]);
  await login(null);
  eq((await db.query('select * from documents where id=$1',[person])).rows.length,1);
  await login(ids.b);
  await call('set_person_consent',[person,false]);
  await login(null);
  eq((await db.query('select * from comments where id=$1',[pc])).rows.length,0);
  await login(ids.admin);
  await call('admin_action',['document',doc,{comments_locked:true,is_locked:true}]);
  await login(ids.b);
  await fail(()=>call('save_document',[{...payload,edit_summary:'잠금'},doc,3]));
  await fail(()=>call('write_comment',[doc,'잠금 댓글',null,null]));
  await login(ids.admin);
  await call('admin_action',['member',ids.b,{is_suspended:true}]);
  await login(ids.b);
  await fail(()=>call('save_document',[payload,null,null]));
  await fail(()=>call('toggle_like',[comment]));
  await login(ids.admin);
  await call('admin_action',['member',ids.b,{is_suspended:false,suspended_until:null}]);
  await call('admin_action',['document',doc,{status:'hidden'}]);
  await login(null);
  eq((await db.query('select * from comments where document_id=$1',[doc])).rows.length,0);
  await login(ids.admin);
  await call('admin_action',['document',doc,{status:'published'}]);
  await call('delete_comment',[comment]);
  eq((await db.query('select content,is_deleted from comments where id=$1',[comment])).rows[0],{content:'삭제된 댓글입니다.',is_deleted:true});
  eq((await db.query('select * from comments where id=$1',[reply])).rows.length,1);
  await db.exec('reset role');
  const count=(await db.query('select count(*)::int n from document_revisions')).rows[0].n;
  await db.exec(schema);await db.exec(schema);
  eq((await db.query('select count(*)::int n from document_revisions')).rows[0].n,count);
  eq((await db.query('select count(*)::int n from categories')).rows[0].n,8);
  const category=(await db.query('select id from categories limit 1')).rows[0].id;
  await db.query('delete from categories where id=$1',[category]);
  await db.exec(schema);
  eq((await db.query('select count(*)::int n from categories')).rows[0].n,7);
  await db.query('delete from auth.users where id=$1',[ids.a]);
  eq((await db.query('select author_id from documents where id=$1',[doc])).rows[0].author_id,null);
  // 以前 버전처럼 컬럼이 누락된 상태에서 재실행 복구.
  await db.exec('alter table profiles drop column cohort; alter table documents drop column edit_summary;');
  await db.exec(schema);
  eq((await db.query("select column_name from information_schema.columns where table_name='documents' and column_name='edit_summary'")).rows.length,1);
  console.log('PASS '+(partial?'부분 설치':'신규 설치')+' / 문서·버전·댓글·동의·관리자·정지·탈퇴·재실행');
 }catch(e){console.error('FAIL:',e.message,e.where||'',e.detail||'');process.exitCode=1;break;}
 finally{await db.close();}
}
console.log('검증 항목:',checks);
