import { useEffect, useMemo, useState } from 'react'
import { supabase, hasSupabaseConfig } from './supabase'
import './App.css'

const demoArticles = [
  { id: 'seunghyeon', category: '학생', title: '김승현', subtitle: '19기 · 소프트웨어개발과', initial: '김', tone: 'coral', views: 127, updated: '오늘, 14:32', excerpt: '웃음이 많고, 새로운 것을 만드는 일을 좋아하는 경소마고 19기 학생.' },
  { id: 'minji', category: '학생', title: '이민지', subtitle: '20기 · 임베디드소프트웨어과', initial: '이', tone: 'blue', views: 93, updated: '어제, 21:04', excerpt: '로봇과 디자인 사이의 재미있는 접점을 탐구하고 있다.' },
  { id: 'webuild', category: '동아리', title: '위빌드', subtitle: '웹 개발 동아리', initial: 'W', tone: 'yellow', views: 210, updated: '9월 16일', excerpt: '학생들의 아이디어를 웹으로 만들어 보는 개발 동아리.' },
  { id: 'festival', category: '학교생활', title: '2026 경소제', subtitle: '경소마고 축제', initial: '축', tone: 'green', views: 365, updated: '9월 12일', excerpt: '모두가 기다리는 경소마고의 가을 축제에 관한 문서.' },
]

function Icon({ name, size = 20 }) {
  const paths = { search: <><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></>, book: <><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H12v16H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M20 5.5A2.5 2.5 0 0 0 17.5 3H12v16h5.5a2.5 2.5 0 0 1 2.5 2.5z"/></>, sparkle: <path d="m12 2 1.7 6.3L20 10l-6.3 1.7L12 18l-1.7-6.3L4 10l6.3-1.7z"/>, edit: <><path d="M12 20h8"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4z"/></>, clock: <><circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3.5 2"/></>, users: <><path d="M16 20v-1.5a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4V20"/><circle cx="9" cy="7" r="4"/><path d="M18 9a3.5 3.5 0 0 0 0-6.5M22 20v-1.5a4 4 0 0 0-3-3.87"/></>, plus: <><path d="M12 5v14M5 12h14"/></>, arrow: <path d="M5 12h14m-6-6 6 6-6 6"/>, more: <><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>, chevron: <path d="m9 18 6-6-6-6"/>, x: <path d="m6 6 12 12M18 6 6 18"/> }
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>
}
function ArticleCard({ article, active, onClick }) { return <button className={`article-card ${active ? 'active' : ''}`} onClick={onClick}><span className={`avatar ${article.tone}`}>{article.initial}</span><span className="card-copy"><small>{article.category}</small><strong>{article.title}</strong><em>{article.subtitle}</em></span><Icon name="chevron" size={17}/></button> }

function App() {
  const [articles, setArticles] = useState(demoArticles); const [selectedId, setSelectedId] = useState('seunghyeon'); const [query, setQuery] = useState(''); const [notice, setNotice] = useState(''); const [menuOpen, setMenuOpen] = useState(false)
  useEffect(() => { if (!hasSupabaseConfig) return; supabase.from('articles').select('*').order('updated_at', { ascending: false }).then(({ data, error }) => { if (!error && data?.length) setArticles(data.map((item, index) => ({ id:item.id, category:item.category || '문서', title:item.title, subtitle:item.subtitle || '경소마고 구성원', initial:item.title?.[0] || '경', tone:['coral','blue','yellow','green'][index % 4], views:item.views || 0, updated:new Date(item.updated_at).toLocaleDateString('ko-KR'), excerpt:item.summary || item.content?.slice(0,80) || '', content:item.content }))) }) }, [])
  const filtered = useMemo(() => articles.filter(a => `${a.title} ${a.category} ${a.subtitle}`.toLowerCase().includes(query.toLowerCase())), [articles, query]); const article = articles.find(a => a.id === selectedId) || articles[0]; const showNotice = text => { setNotice(text); window.setTimeout(() => setNotice(''), 2400) }
  return <div className="app-shell"><header className="topbar"><a className="brand" href="#top" onClick={() => setSelectedId('seunghyeon')}><span className="brand-mark">경</span><span>경소위키백과</span><small>BETA</small></a><div className="top-actions"><button className="write-button" onClick={() => showNotice('문서 작성 기능을 준비하고 있어요.')}><Icon name="edit" size={17}/> 문서 작성</button><button className="profile" onClick={() => setMenuOpen(!menuOpen)}><span>김</span><i>⌄</i></button>{menuOpen && <div className="profile-menu"><b>김승현</b><small>경소마고 19기</small><button onClick={() => showNotice('로그아웃 기능을 연결할 수 있어요.')}>로그아웃</button></div>}</div></header>
  <main id="top"><section className="hero"><div className="hero-grid"/><div className="hero-inner"><div className="eyebrow"><Icon name="sparkle" size={15}/> GBSW STUDENT WIKI</div><h1>경소마고의 모든 이야기,<br/><em>우리 손으로 기록해요.</em></h1><p>친구, 동아리, 학교생활까지. 경북소프트웨어마이스터고등학교의<br className="desktop"/> 오늘을 함께 만들고 기록하는 우리만의 위키백과입니다.</p><label className="search-box"><Icon name="search"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="궁금한 내용을 검색해 보세요"/><kbd>⌘ K</kbd></label><div className="hero-meta"><span><b>326</b>개의 문서</span><i/><span>최근 7일간 <b>48</b>명이 편집했어요</span></div></div><div className="flag-logo">⚑</div><div className="floating-note note-one"><span className="mini-avatar blue">이</span><div><b>이민지 님이 편집</b><small>“인공지능 동아리”</small></div><time>2분 전</time></div><div className="floating-note note-two"><span className="mini-avatar coral">박</span><div><b>박서준 님이 새 문서 작성</b><small>“2026 경소제”</small></div><time>12분 전</time></div></section>
  <section className="content-wrap"><div className="section-heading"><div><span className="section-kicker">EXPLORE</span><h2>요즘 많이 보는 문서</h2></div><button onClick={() => showNotice('전체 문서 목록을 준비하고 있어요.')}>전체 문서 보기 <Icon name="arrow" size={17}/></button></div><div className="explore-grid"><div className="article-list">{filtered.length ? filtered.map(item => <ArticleCard key={item.id} article={item} active={item.id === article?.id} onClick={() => setSelectedId(item.id)}/>) : <div className="empty">검색 결과가 없어요.</div>}</div>{article && <article className="article-preview"><div className="preview-top"><span className={`avatar large ${article.tone}`}>{article.initial}</span><span className="topic">{article.category}</span><button onClick={() => showNotice('더보기 메뉴를 준비하고 있어요.')}><Icon name="more"/></button></div><h3>{article.title}</h3><p className="preview-subtitle">{article.subtitle}</p><div className="article-rule"/><p className="article-text">{article.content || article.excerpt}</p><div className="article-bottom"><span><Icon name="clock" size={16}/> 마지막 편집 {article.updated}</span><span>{article.views}회 열람</span></div><button className="read-more" onClick={() => showNotice(`“${article.title}” 문서를 열었어요.`)}>문서 읽기 <Icon name="arrow" size={17}/></button></article>}</div></section>
  <section className="community"><div className="community-inner"><div className="community-icon"><Icon name="users" size={25}/></div><div><span className="section-kicker">COMMUNITY</span><h2>처음이라도 괜찮아요.</h2><p>누구나 문서를 만들고, 더 정확하게 고칠 수 있어요.<br/>우리의 이야기를 더 풍성하게 만들어 주세요.</p></div><button className="community-cta" onClick={() => showNotice('환영합니다! 첫 문서를 작성해 보세요.')}><Icon name="plus" size={18}/> 첫 문서 작성하기</button></div></section></main>
  <footer><div className="footer-brand"><span className="brand-mark">경</span> 경소위키백과</div><p>경북소프트웨어마이스터고등학교 학생들이 함께 만드는 공간</p><span>© 2026 GBSW Wiki</span></footer>{notice && <div className="toast">{notice}<button onClick={() => setNotice('')}><Icon name="x" size={16}/></button></div>}</div>
}
export default App
